services:
  - type: web
    name: brainwave-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_EMAIL
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
